name: CD - Deploy to Minikube
on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"] # Use the 'name' from ci.yml
    types:
      - completed # This means 'cd.yml' will only run after 'ci.yml' finishes

jobs:
  deploy:
    runs-on: self-hosted
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Kubeconfig
        run: |
          echo "${{ secrets.KUBE_CONFIG_DATA }}" | base64 -d > ~/.kube/config
          kubectl config set-context minikube

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout restart deployment/url-shortener