name: CD - Deploy to Minikube
on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Minikube
        uses: medyagh/setup-minikube@master # This action installs both Minikube and kubectl, starts minikube using docker driver and sets the kubectl context
        with:
          kubernetes-version: 'v1.33.1' # Specify a stable Kubernetes version you prefer

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl apply -f k8s/service.yaml
          kubectl rollout restart deployment/url-shortener

          echo "Giving application a moment to fully start up after rollout..."
          sleep 20 # Add a sleep here (e.g., 15-20 seconds) as an extra buffer

      - name: Port-forward and test the URL shortener API
        run: |
          # Port-forward the service or deployment
          kubectl port-forward deployment/url-shortener 3000:3000 &
          sleep 5  # Wait for the port-forward to be ready

          echo "Testing whether long URL converts into Short URL "
          curl -s -X POST http://localhost:3000/shorten \
            -H "Content-Type: application/json" \
            -d '{"url": "https://thisisthelongurl.com"}' > response.json

          cat response.json
          SHORT_URL=$(jq -r '.short_url' response.json)

          echo "Testing GET to short URL: $SHORT_URL"
          curl -v "$SHORT_URL"
