name: CD - Deploy to Minikube
on:
  workflow_run:
    workflows: ["CI - Build & Push Docker Image"]
    types:
      - completed

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Install kubectl
        run: |
          curl -LO "https://dl.k8s.io/release/$(curl -s https://dl.k8s.io/release/stable.txt)/bin/linux/amd64/kubectl"
          chmod +x kubectl
          sudo mv kubectl /usr/local/bin/

      - name: Install Minikube
        run: |
          curl -Lo minikube https://storage.googleapis.com/minikube/releases/latest/minikube-linux-amd64
          chmod +x minikube
          sudo mv minikube /usr/local/bin/

      - name: Start Minikube with Docker Driver
        run: |
          sudo minikube start --driver=docker
          minikube status

      - name: Set kubectl context to Minikube
        run: |
          kubectl config use-context minikube

      - name: Apply Kubernetes Manifests
        run: |
          kubectl apply -f k8s/deployment.yaml
          kubectl rollout restart deployment/url-shortener

      - name: Port-forward and test the URL shortener API
        run: |
          # Port-forward the service or deployment
          kubectl port-forward deployment/url-shortener 3000:3000 &
          sleep 5  # Wait for the port-forward to be ready

          echo "Testing whether long URL converts into Short URL "
          curl -s -X POST http://localhost:3000/shorten \
            -H "Content-Type: application/json" \
            -d '{"url": "https://thisisthelongurl.com"}' > response.json

          cat response.json
          SHORT_URL=$(jq -r '.short_url' response.json)

          echo "Testing GET to short URL: $SHORT_URL"
          curl -v "$SHORT_URL"
